name: Xcode build iOS 16

on: [push, pull_request]

jobs:
  Build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode iOS build
      run: |
        cd Xcode/
        xcodebuild clean build -scheme FastMDb -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'
