name: Xcode test

on: [push, pull_request]

jobs:
  Test:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode unit tests
      run: |
        cd Xcode/
        xcodebuild clean test -scheme FastMDb -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.2' -resultBundlePath TestResults

    - uses: actions/upload-artifact@v2
      with:
        path: Xcode/TestResults.xcresult
        
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: Xcode/TestResults.xcresult
      if: success() || failure()
